### ISSUE TITLE
Usage in Nuxt app

### ISSUE THREAD

**Issue by idzubans** [supraniti/vue-dnd-zone#2]
Hey, thank you for the package. I wonder if you can provide a simple guide how to import this package in a Nuxt application.

**Comment by JoeEarly** [comment]
Add it as a plugin https://nuxtjs.org/docs/2.x/directory-structure/plugins/

**Comment by supraniti** [comment]
Can be added to a nuxt project like any other vue plugin

**Comment by cdefy** [comment]
Hi there,

First thanks for your work @supraniti :)
Like @idzubans I'm trying to make vue-dnd-zone works with Nuxt. I'm not a pro with Nuxt or Vue but after trying around, I managed something. So I will share for others.

I added it as a plugin with those lines (following the doc @JoeEarly pointed):
```
import Vue from 'vue'
import VueDndZone from 'vue-dnd-zone'

Vue.use(VueDndZone)
```
And in nuxt.config.js :
`plugins: [{ src: '~/plugins/vue-dnd-zone.js', ssr: false }],`
`css: ['@/node_modules/vue-dnd-zone/vue-dnd-zone.css'],`

By using the code showed [here](https://supraniti.github.io/vue-dnd-zone/) (the grid one) and adding data in script, I managed to have something working. It's a start!

But I've got a DOM error in the browser console :
`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

Although it will be reaaaally helpful if you show the complete code (template, script and css) for all your examples (list, grid, nested grid and especially the one on About page) :)

Thanks a lot in advance for any help and your time.
BR
